#include "../tools/Demonstration.h"
#include "gameplay/Game.h"
#include <algorithm>
#include <cmath>
#include <iostream>

namespace shooter::demo {
namespace {
std::string maskName(int mask) {
    std::string result;
    const char* names[]={"ambient","sun","points","spots"};
    for(int i=0;i<4;++i) if(mask&(1<<i)) result+=(result.empty()?"":" + ")+std::string(names[i]);
    return result.empty()?"no light sources":result;
}
void calculation(std::ostream& out,Vec3 p,Vec3 n,Vec3 eye,const LightingRig& rig,float ks,float shine) {
    n=normalize(n);const auto v=normalize(eye-p);Vec3 diffuse=rig.ambient,specular{};
    out<<"\nAt world surface P="<<vector(p)<<", N="<<vector(n)<<", eye="<<vector(eye)
       <<", V=normalize(eye-P)="<<vector(v)<<", ks="<<number(ks)<<", shininess="<<number(shine)<<".\n\n"
         "| Source | L | d | attenuation | cone dot | smoothstep | N dot L (clamped) | R dot V (clamped) | Diffuse RGB increment | Specular RGB increment |\n"
         "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |\n";
    auto add=[&](const std::string& name,Vec3 l,Vec3 color,float d,float attenuation,float cone,float intensity) {
        const float ndl=std::max(0.f,dot(n,l));const auto r=n*(2*dot(n,l))-l;
        const float rdv=std::max(0.f,dot(r,v));
        const auto cd=color*(attenuation*intensity*ndl);
        const auto cs=color*(attenuation*intensity*(ndl>0?ks*std::pow(rdv,shine):0));
        diffuse=diffuse+cd;specular=specular+cs;
        out<<"| "<<name<<" | "<<vector(l)<<" | "<<number(d)<<" | "<<number(attenuation)<<" | "<<number(cone)
           <<" | "<<number(intensity)<<" | "<<number(ndl)<<" | "<<number(rdv)<<" | "<<vector(cd)<<" | "<<vector(cs)<<" |\n";
    };
    add("sun",normalize(rig.sunDirection),rig.sunColor,0,1,1,1);
    for(std::size_t i=0;i<rig.points.size();++i) {
        const auto& l=rig.points[i]; const auto delta=l.position-p;const float d=std::max(length(delta),.001f);
        add("point "+std::to_string(i),delta*(1/d),l.color,d,1/(1+.09f*d+.032f*d*d),1,1);
    }
    for(std::size_t i=0;i<rig.spots.size();++i) {
        const auto& l=rig.spots[i]; const auto delta=l.position-p;const float d=std::max(length(delta),.001f);
        const float cone=dot(delta*(-1/d),l.direction);
        const float t=std::clamp((cone-l.outerCos)/(l.innerCos-l.outerCos),0.f,1.f);
        add("spot "+std::to_string(i),delta*(1/d),l.color,d,1/(1+.025f*d+.002f*d*d),cone,t*t*(3-2*t));
    }
    out<<"\nD (including ambient) = "<<vector(diffuse)<<"; S = "<<vector(specular)<<". "
         "For this surface's actual sampled texture RGB Q and tint C, base=B=C*Q, so the exact remaining expression is "
         "gamma(clamp((B*D+S)*(1-e)+B*e,0,1)). Texture filtering Q is performed by the GPU; "
         "the table does not invent a texture sample or claim to be a measured framebuffer pixel.\n";
}
}
void demonstrateLighting(Capture& capture,const fs::path& root,const Catalogue& examples) {
    std::cout<<"Demonstrating lighting: day/night x 3 shading modes x 16 source masks\n";
    auto out=document(root/"lighting"/"lighting.md");const auto dir=root/"lighting";
    out<<"# Exact game lighting demonstration\n\n"
         "Generated by `lighting/demonstrateLighting.cpp` using the game's Renderer, shader files, textures, "
         "createLighting and Game::scene. No alternate lighting renderer is used for images. "
         "All source code listings below are read from the current checkout on each build.\n\n"
         "## Coverage and interpretation\n\n"
         "There are two actual lighting presets (day/night), three shading modes (flat/Gouraud/Phong), "
         "and four source families (ambient/directional/point/spot). The grid exhausts their 2 x 3 x 16 discrete combinations. "
         "Mask 15 is the unmodified game state. Other masks are diagnostic source removal, not additional gameplay presets. "
         "Day has zero point/spot intensity; night has zero sun intensity. Consequently some comparisons are intentionally identical. "
         "Positions, viewing angles and material values are continuous, so no finite image collection can cover every possible pixel/view. "
         "Additional close views, all fixtures, material examples, emission, flash, and spotlight edge cases follow. "
         "The sky and emissive objects remain visible even with mask 0; the mask only removes illumination terms.\n\n"
         "## Implemented equations\n\n"
         "M = T Rz Ry Rx H S; Pworld=M Plocal; N=normalize(transpose(inverse(mat3(M))) Nlocal); "
         "V=normalize(eye-Pworld). The renderer uploads the normal matrix using cofactor columns divided by det(M).\n\n"
         "For each light, a=max(dot(N,L),0); R=reflect(-L,N)=2 dot(N,L) N-L. "
         "Diffuse increment = color*a. Specular increment = color*ks*max(dot(R,V),0)^shininess when a>0, otherwise zero. "
         "This is Phong reflection; there is no halfway vector. Ambient initializes the diffuse accumulator.\n\n"
         "Directional: L=normalize(sunDirection), without distance attenuation. "
         "Point: delta=lightPosition-Pworld, d=max(length(delta),0.001), L=delta/d, A=1/(1+0.09d+0.032d²). "
         "Spot: A=1/(1+0.025d+0.002d²), c=dot(-L,spotDirection), "
         "t=clamp((c-cos(53°))/(cos(32°)-cos(53°)),0,1), I=t²(3-2t). "
         "Point color is multiplied by A; spot color by A*I. All 8 points and 6 spots add independently.\n\n"
         "Texture base B=surfaceColor*texture(materialTextures,(UV,layer)). "
         "UV comes from (localPosition+0.5)*abs(scale)*textureScale, selecting XZ on Y faces, ZY on X faces, XY on Z faces. "
         "Layer=Plain for emission>0.5, else Paper for targetPattern, else the material layer. "
         "Llit=B*diffuse+specular; emission blends (1-e)*Llit+e*B; output RGB=pow(clamp(result,0,1),1/2.2). "
         "Emission changes the object's own appearance and does not illuminate neighboring objects. "
         "The implementation has no shadow mapping, occlusion, distance fog, bloom, physically based BRDF, or tone mapping beyond clamp/gamma.\n\n"
         "Flat computes light at the triangle's provoking vertex and holds it constant; Gouraud interpolates vertex lighting; "
         "Phong computes lighting per fragment using interpolated world position and normal. "
         "The cube has separate face normals; Phong does not round cube edges. Texture and target-ring lookup stay per fragment in all modes.\n\n"
         "Target rings: shapePosition=localPosition*patternScale+patternOffset; radius=2*length(shapePosition.xy); "
         "ring=clamp(int(radius*6),0,5); fract(radius*6)>0.95 draws a dark boundary. "
         "Only local +Z faces print rings; other faces return (0.15,0.18,0.21). "
         "Flash mixes the ring color toward (1,0.76,0.2) by hitTime/0.25*0.5. Exact ring colors appear in object.frag below.\n\n";
    Game game; game.startMode(GameMode::Developer,7);
    const View overview{{0,28,8},{0,0,-45},.05f,250};
    const View close{{-12,7,-4},{-18,2,-14},.05f,250};
    out<<"## Complete source-family combinations\n\nOverview eye="<<vector(overview.eye)<<", center="<<vector(overview.center)
       <<"; close eye="<<vector(close.eye)<<", center="<<vector(close.center)<<". FOV 45°, aspect 4/3, near 0.05, far 250. "
         "All scene transforms stay at level 7 startup. Day/night also updates lens emission and celestial geometry through Game::scene.\n\n";
    const char* shadingNames[]={"Flat","Gouraud","Phong"};
    for(bool night:{false,true}) {
        game.night=night;const auto scene=game.scene(true);const auto rig=createLighting(night);
        out<<"\n## "<<(night?"Night":"Day")<<" preset values\n\nAmbient="<<vector(rig.ambient)<<", sun direction="<<vector(rig.sunDirection)<<", sun color="<<vector(rig.sunColor)<<".\n\n"
             "| Light | Position | Direction | Color | Inner cosine | Outer cosine |\n| --- | --- | --- | --- | ---: | ---: |\n";
        for(std::size_t i=0;i<rig.points.size();++i) {const auto& l=rig.points[i];out<<"| Point "<<i<<" | "<<vector(l.position)<<" | omnidirectional | "<<vector(l.color)<<" | — | — |\n";}
        for(std::size_t i=0;i<rig.spots.size();++i) {const auto& l=rig.spots[i];out<<"| Spot "<<i<<" | "<<vector(l.position)<<" | "<<vector(l.direction)<<" | "<<vector(l.color)<<" | "<<number(l.innerCos)<<" | "<<number(l.outerCos)<<" |\n";}
        for(int shading=0;shading<3;++shading) {
            out<<"\n### "<<(night?"Night":"Day")<<" / "<<shadingNames[shading]<<"\n\n"
                 "Each row retains exactly the named terms of the equation. Compare the same column across rows to see their additive contribution.\n\n"
                 "| Mask / sources | Arena overview | Close view |\n| --- | --- | --- |\n";
            for(int mask=0;mask<16;++mask) {
                const auto stem=std::string(night?"night":"day")+"-"+std::to_string(shading)+"-mask-"+std::to_string(mask);
                capture.save(dir/(stem+".png"),scene,overview,night,mask,shading);
                capture.save(dir/(stem+"-close.png"),scene,close,night,mask,shading);
                out<<"| "<<mask<<": "<<maskName(mask)<<(mask==15?" (game preset)":"")<<" | !["<<stem<<"]("<<stem<<".png) | ![Close "<<stem<<"]("<<stem<<"-close.png) |\n";
            }
        }
        out<<"\n### Worked calculation: floor below warm spawn lamp\n";
        calculation(out,{-18,0,-12},{0,1,0},close.eye,rig,.12f,24);
    }
    out<<"\n## Point falloff and spotlight cone samples\n\nThese views inspect actual floor positions using the unchanged night scene and Phong shader. "
         "The camera is moved for inspection; no lights are moved or recolored. The numeric evaluations use floor normal (0,1,0), ks=0.12 and exponent 24.\n";
    game.night=true;const auto scene=game.scene(true);const auto rig=createLighting(true);
    for(float distance:{1.f,5.f,12.f}) {
        const Vec3 p{-18+distance,0,-12};const View view{p+Vec3{3,4,5},p,.05f,250};
        const auto file="point-floor-offset-"+std::to_string(int(distance))+".png";
        capture.save(dir/file,scene,view,true,4);
        out<<"\n### Floor offset "<<distance<<" m from lamp's ground projection\n\n![Point attenuation]("<<file<<")\n";
        calculation(out,p,{0,1,0},view.eye,rig,.12f,24);
    }
    const auto& spot=rig.spots.front();
    const auto side=normalize(cross(spot.direction,{0,1,0}));
    for(float angle:{0.f,32.f,42.5f,53.f,60.f}) {
        const auto ray=spot.direction*std::cos(radians(angle))+side*std::sin(radians(angle));
        const auto p=spot.position+ray*(-spot.position.y/ray.y);
        const View view{p+Vec3{3,5,6},p,.05f,250};const auto file="spot-angle-"+slug(number(angle))+".png";
        capture.save(dir/file,scene,view,true,8);
        out<<"\n### "<<angle<<"° from spot 0 axis\n\n![Spot cone sample]("<<file<<")\n\n"
             "The center is the intersection of the angled ray with Y=0. "
             "0°/32° are in the full cone, 42.5° is the smooth transition, and 53°/60° receive zero from spot 0. "
             "Other active spots can still illuminate this point; some ray intersections fall beyond the arena floor.\n";
        calculation(out,p,{0,1,0},view.eye,rig,.12f,24);
    }
    out<<"\n## Each physical fixture\n\nClose night views retain all lighting. A bright lens is an emissive cube; the point/spot parameters above are the separate illumination source.\n\n";
    for(std::size_t i=0;i<rig.points.size()+rig.spots.size();++i) {
        const Vec3 p=i<rig.points.size()?rig.points[i].position:rig.spots[i-rig.points.size()].position;
        const View view{p+Vec3{p.x<0?4.f:-4.f,2,5},p,.05f,250};const auto file="fixture-"+std::to_string(i)+".png";
        capture.save(dir/file,scene,view,true);
        out<<"### "<<(i<8?"Point ":"Spot ")<<(i<8?i:i-8)<<"\n\n![Fixture]("<<file<<")\n\n";
    }
    out<<"\n## Materials, emission and transient appearance\n\nThese use original object values and positions. "
         "Object-only captures omit surrounding geometry for inspection, but keep the complete day/night light rig. "
         "Without shadowing, removing neighboring geometry does not change a surface's illumination.\n\n";
    for(const auto& [name,ex]:examples) {
        std::vector<std::pair<std::string,std::vector<SceneObject>>> cases{{"base",ex.parts}};
        for(const auto& [state,parts]:ex.states) if(state=="fired-recoil-1" || state=="hit-flash-0-25" || state=="respawn-countdown-2") cases.push_back({state,parts});
        for(const auto& [state,parts]:cases) {
            out<<"### "<<name<<" / "<<state<<"\n\n[Exact component material parameters and construction](../objects/"<<name<<"/"<<name<<".md).\n\n"
                 "| Shading | Day | Night |\n| --- | --- | --- |\n";
            for(int shading=0;shading<3;++shading) {
                out<<"| "<<shadingNames[shading]<<" | ";
                for(bool night:{false,true}) {
                    auto objects=parts;
                    for(auto& o:objects) if(o.type=="Lighting" && o.component=="Lens") {
                        o.emission=night?1:0;
                        if(!night) o.color={.22f,.25f,.28f};
                        else for(const auto& fixture:createLightFixtures()) if(fixture.id==o.id) o.color=fixture.color;
                    }
                    const auto file="material-"+name+"-"+state+"-"+std::to_string(shading)+(night?"-night.png":"-day.png");
                    // The sun is absent at night in the actual game.
                    if(night && name=="environment-sun-visual") objects.clear();
                    capture.save(dir/file,objects,fit(parts),night,15,shading);
                    out<<"!["<<(night?"Night":"Day")<<"]("<<file<<") | ";
                }
                out<<"\n";
            }
        }
    }
    out<<"\n## Procedural sky\n\nThe sky is a fullscreen triangle with depth writes/testing disabled. "
         "It does not use the scene's camera direction or lighting equation. "
         "RGB=mix(horizon,zenith,smoothstep(0.15,1,uv.y)); day horizon=(0.67,0.81,0.93), zenith=(0.20,0.48,0.78); "
         "night horizon=(0.045,0.065,0.12), zenith=(0.006,0.012,0.04). Sky output is not passed through object gamma.\n\n";
    for(bool night:{false,true}) {
        const auto file=std::string(night?"sky-night.png":"sky-day.png");capture.save(dir/file,{},overview,night);
        out<<"!["<<file<<"]("<<file<<")\n\n";
    }
    out<<"## Exact source and how it connects\n\n"
         "Lighting.cpp constructs the numeric rig and visible fixtures. Renderer.cpp selects day/night, applies the diagnostic mask, "
         "uploads uniforms, builds the inverse-transpose normal matrix, selects texture layers/repeats and draws the unit cube. "
         "object.vert transforms geometry and optionally computes vertex lighting. lighting.glsl accumulates the formulas above. "
         "object.frag selects flat/interpolated/per-fragment results, applies surface texture, emission, clamp and gamma. "
         "sky.frag is an independent background pass. TextureCache and Material define the actual image sampling and material assignments.\n";
    for(const auto& file:{"src/world/Lighting.cpp","src/rendering/Renderer.cpp","shaders/lighting.glsl","shaders/object.vert","shaders/object.frag","shaders/sky.vert","shaders/sky.frag","src/core/Material.h","src/rendering/TextureCache.cpp"}) source(out,root,file);
}
}
