#include "gameplay/Game.h"
#include <algorithm>
#include <array>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
using namespace shooter;
namespace {
// Print XYZ with three decimal places for the generated scene reference.
std::string vector(Vec3 v) { std::ostringstream s; s<<std::fixed<<std::setprecision(3)<<'('<<v.x<<", "<<v.y<<", "<<v.z<<')'; return s.str(); }
// Take the smaller coordinate on each axis to accumulate lower bounds.
Vec3 minimum(Vec3 a,Vec3 b) { return {std::min(a.x,b.x),std::min(a.y,b.y),std::min(a.z,b.z)}; }
// Take the larger coordinate on each axis to accumulate upper bounds.
Vec3 maximum(Vec3 a,Vec3 b) { return {std::max(a.x,b.x),std::max(a.y,b.y),std::max(a.z,b.z)}; }
struct Group {
    std::array<int,7> counts{};
    Vec3 lowSize{1e6f,1e6f,1e6f},highSize{},lowPosition{1e6f,1e6f,1e6f},highPosition{-1e6f,-1e6f,-1e6f};
};
}
// Measure real level builders and export cube counts, component ranges, and target-motion settings.
int main(int argc,char** argv) {
    if(argc!=2) { std::cerr<<"Usage: scene_reference OUTPUT.md\n"; return 1; }
    std::ofstream out(argv[1]); if(!out) return 1;
    out<<"# Generated scene reference\n\nGenerated by `tools/scene_reference.cpp` from the actual shared model builders and level configurations. "
          "Units are meters; tuples are X/Y/Z. Counts are initial daytime cube instances with the player avatar and pistol included, "
          "plus the three equipment-display weapons. These are measured scene values, not manually maintained estimates. "
          "Moving objects change after startup. Component scales precede shear/rotation; position bounds describe component centers at time zero, not occupied extents.\n\n"
          "Rebuild/regenerate: `cmake --build build/lighting-final --target scene_reference`, then "
          "`./build/lighting-final/scene_reference.exe docs/scene-reference.md`.\n\n"
          "## Initial populations\n\n| Level | Crate assemblies | Cargo cubes | Targets | Birds | Humans | All scene cubes |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n";
    std::map<std::string,Group> groups;
    for(int level=1;level<=7;++level) {
        Game game; game.startMode(GameMode::Developer,level); const auto scene=game.scene(true);
        int crates=0,cargo=0;
        for(const auto& o:scene) {
            crates+=o.type=="Cargo"&&o.component=="Crate"; cargo+=o.type=="Cargo";
            auto key=o.type+" / "+o.component;
            if(o.type=="Weapon") key+=" / "+std::string(o.id.find("PISTOL")!=std::string::npos?"Pistol":o.id.find("SHOTGUN")!=std::string::npos?"Shotgun":"Rifle");
            auto& group=groups[key]; ++group.counts[level-1];
            group.lowSize=minimum(group.lowSize,o.transform.scale); group.highSize=maximum(group.highSize,o.transform.scale);
            group.lowPosition=minimum(group.lowPosition,o.transform.position); group.highPosition=maximum(group.highPosition,o.transform.position);
        }
        out<<"| "<<level<<" | "<<crates<<" | "<<cargo<<" | "<<game.targets.size()<<" | "<<game.birds.size()<<" | "<<game.humans.size()<<" | "<<scene.size()<<" |\n";
    }
    out<<"\nFree and Bird's-Eye reuse Level 7. Bird's-Eye additionally draws two observation reference cubes. "
         "First-person rendering hides four avatar cubes. Night removes the sun cube; no moon is drawn (-1). "
         "Selecting shotgun/rifle replaces the pistol's 11 parts with 14/15; muzzle flash temporarily adds one. "
         "Dead bodies retain their original component counts; blood, fragments and celebration cubes are transient. "
         "NPC counts are initial populations, not a respawn guarantee.\n\n"
         "## Every starting component category\n\nCounts column is L1 / L2 / L3 / L4 / L5 / L6 / L7. "
         "Identical size endpoints mean a fixed component size. Ranges summarize actual variants across these scenes. "
         "For a single named instance's translation/rotation/shear/color/material and world point, use its live `calc.csv` row.\n\n"
         "| Type / component | Counts L1-L7 | Scale minimum to maximum | Initial center minimum to maximum |\n"
         "| --- | --- | --- | --- |\n";
    for(const auto& [name,g]:groups) {
        out<<"| "<<name<<" | "; for(int i=0;i<7;++i) out<<(i?" / ":"")<<g.counts[i];
        out<<" | "<<vector(g.lowSize)<<" to "<<vector(g.highSize)<<" | "<<vector(g.lowPosition)<<" to "<<vector(g.highPosition)<<" |\n";
    }
    out<<"\n## Exact level target configuration\n\nBase is the movement center; actual time-zero position includes the phase offset. "
         "Axes with zero amplitude remain fixed. Frequencies are radians/second; spin is signed degrees/second. "
         "Position = base + amplitude * sin(time * frequency + phase), component by component.\n\n"
         "| Level / target | Base | Amplitude | Frequency | Phase (radians) | Y spin (deg/s) |\n| --- | --- | --- | --- | --- | ---: |\n";
    for(int level=1;level<=7;++level) {
        const auto c=levelConfiguration(level);
        for(std::size_t i=0;i<c.targets.size();++i) { const auto& t=c.targets[i];
            out<<"| "<<level<<" / "<<i+1<<" | "<<vector(t.base)<<" | "<<vector(t.motion.amplitude)<<" | "<<vector(t.motion.frequency)<<" | "<<vector(t.motion.phase)<<" | "<<t.motion.spinSpeed<<" |\n";
        }
    }
    out.close(); return out?0:1;
}
